languageCode = "en-us"
license = "APL 2"
title = "dex.js : Javascript Data Visualization"
baseurl = "/"
theme = "dexjs-theme"
features = [ "disqus", "google analytics", "share" ]
disqusShortName = "dexjs"
sectionPagesMenu = "main"

enableRobotsTXT = true
googleAnalytics = "UA-89686420-1"

[author]
  name = "Patrick Martin"
  homepage = "https://dexjs.net/"

[params]
  custom_css = ["css/custom.css"]

[page]
  css = []

[menu]
  [[menu.main]]
    name = "Home"
    pre = ""
    identifier = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Examples"
    pre = ""
    identifier = "examples"
    url = "/examples.html"
    weight = 3
  [[menu.main]]
    name = "Posts"
    pre = ""
    identifier = "posts"
    url = "/posts.html"
    weight = 4
  [[menu.main]]
    name = "Docs"
    pre = ""
    identifier = "docs"
    url = "/docs.html"
    weight = 5
  [[menu.main]]
    name = "Links"
    pre = ""
    identifier = "links"
    url = "/links.html"
    weight = 6
  [[menu.main]]
    name = "About"
    pre = ""
    identifier = "about"
    url = "/about.html"
    weight = 7
  [[menu.main]]
    name = "Github"
    pre = ""
    identifier = "github"
    url = "https://github.com/PatMartin/dexjs"
    weight = 8
