name = "dex.js Site"
license = "APL 2.0"
licenselink = "https://github.com/PatMartin/dexjs-site/LICENSE.md"
description = "dex.js theme."
homepage = "https://github.com/PatMartin/dexjs-site"
tags = ["hugo"]
features = []
min_version= 0.9

[author]
  name = "Patrick Martin"
  homepage = "http://dexjs.net"

# If porting an existing theme
[original]
  name = "Patrick Martin"
  repo = "https://github.com/PatMartin"
